### ISSUE TITLE
mediawiki: new users can't log in to the wiki

### ISSUE THREAD

**Issue by tingox** [bitraf/infrastructure#122]
A new (newly created user in p2k16) user is supposed to be able to log in to the wiki. Instead they get an error message

> Autooprrettelse av lokal konto mislyktes: 
> Automatisk kontoopprettelse tillates ikke.

The list of users on the wiki shows that new users hasn't been created since 2018-11-08. The code that allows our mediawiki to use p2k16 as an authentication source (p2k12-auth.php) is mature and hasn't changed in years. Likewise, mediawiki configuration parameters related to authentication have been unchanged for years.

So the most likely explanation is that something has changed in MediaWiki itself. We are currently using version 1.32.

p2k12-auth.php uses [AuthPlugin](https://www.mediawiki.org/wiki/AuthPlugin), which MediaWiki has marked as deprecated since version 1.27.

**Comment by tingox** [comment]
as a local (= on the mediawiki machine only) test, I've tried changing the parameter `$autocreate=false` to `$autocreate=true` in the function `initUser()` in `p2k12-auth.php`, but that didn't have any effect.

**Comment by tingox** [comment]
I also tried setting `$wgGroupPermissions['*']['autocreateaccount'] = true;` in `LocalSettings.php` but then I Got a MedaWiki internal error:
```
Original exception: [d023c36a8d5f3aa89dda7659] /w/index.php?title=Spesial:Logg_inn&returnto=Forside Wikimedia\Rdbms\DBQueryError from line 1496 of /opt/mediawiki/mediawiki/includes/libs/rdbms/database/Database.php: A database query error has occurred. Did you forget to run your application's database schema updater after upgrading? 
Query: INSERT INTO "mwuser" (user_name,user_password,user_newpassword,user_email,user_email_authenticated,user_real_name,user_token,user_registration,user_editcount,user_touched) VALUES ('Tingo-test','','','',NULL,'','63ee74de94fabbf95b75103c126d6a27','2019-03-26 15:43:54+00','0','2019-03-26 15:43:59+00')
Function: User::addToDatabase
Error: 23502 ERROR: null value in column "user_id" violates not-null constraint
DETAIL: Failing row contains (null, Tingo-test, , , , null, 63ee74de94fabbf95b75103c126d6a27, , null, null, null, null, 2019-03-26 15:43:59+00, 2019-03-26 15:43:54+00, 0, null).
```
that doesn't look good.

**Comment by tingox** [comment]
data point: p2k16 was put into production at 2018-05-09.

**Comment by tingox** [comment]
If I try to create a user manually in Mediawiki, I get an error message
```
MediaWiki internal error.

Original exception: [e87d59dbc125b0732b0ec253] /wiki/Spesial:Opprett_konto Wikimedia\Rdbms\DBQueryError from line 1496 of /opt/mediawiki/mediawiki/includes/libs/rdbms/database/Database.php: A database query error has occurred. Did you forget to run your application's database schema updater after upgrading? 
Query: INSERT INTO "mwuser" (user_name,user_password,user_newpassword,user_email,user_email_authenticated,user_real_name,user_token,user_registration,user_editcount,user_touched) VALUES ('Tingo-test2','','','',NULL,'Torfinn Testbruker2','238f5b8d9ed99762deb73777c3567b88','2019-04-29 19:16:55+00','0','2019-04-29 19:17:00+00')
Function: User::addToDatabase
Error: 23502 ERROR: null value in column "user_id" violates not-null constraint
DETAIL: Failing row contains (null, Tingo-test2, Torfinn Testbruker2, , , null, 238f5b8d9ed99762deb73777c3567b88, , null, null, null, null, 2019-04-29 19:17:00+00, 2019-04-29 19:16:55+00, 0, null).
```
and a backtrace
```
Backtrace:
#0 /opt/mediawiki/mediawiki/includes/libs/rdbms/database/Database.php(1466): Wikimedia\Rdbms\Database->makeQueryException(string, string, string, string)
#1 /opt/mediawiki/mediawiki/includes/libs/rdbms/database/Database.php(1226): Wikimedia\Rdbms\Database->reportQueryError(string, string, string, string, boolean)
#2 /opt/mediawiki/mediawiki/includes/libs/rdbms/database/DatabasePostgres.php(631): Wikimedia\Rdbms\Database->query(string, string)
#3 /opt/mediawiki/mediawiki/includes/user/User.php(4400): Wikimedia\Rdbms\DatabasePostgres->insert(string, array, string, array)
#4 /opt/mediawiki/mediawiki/includes/libs/rdbms/database/Database.php(3805): User->{closure}(Wikimedia\Rdbms\DatabasePostgres, string)
#5 /opt/mediawiki/mediawiki/includes/user/User.php(4428): Wikimedia\Rdbms\Database->doAtomicSection(string, Closure)
#6 /opt/mediawiki/mediawiki/includes/auth/AuthManager.php(1415): User->addToDatabase()
#7 /opt/mediawiki/mediawiki/includes/auth/AuthManager.php(1142): MediaWiki\Auth\AuthManager->continueAccountCreation(array)
#8 /opt/mediawiki/mediawiki/includes/specialpage/AuthManagerSpecialPage.php(358): MediaWiki\Auth\AuthManager->beginAccountCreation(User, array, string)
#9 /opt/mediawiki/mediawiki/includes/specialpage/AuthManagerSpecialPage.php(482): AuthManagerSpecialPage->performAuthenticationStep(string, array)
#10 /opt/mediawiki/mediawiki/includes/htmlform/HTMLForm.php(665): AuthManagerSpecialPage->handleFormSubmit(array, VFormHTMLForm)
#11 /opt/mediawiki/mediawiki/includes/specialpage/AuthManagerSpecialPage.php(416): HTMLForm->trySubmit()
#12 /opt/mediawiki/mediawiki/includes/specialpage/LoginSignupSpecialPage.php(317): AuthManagerSpecialPage->trySubmit()
#13 /opt/mediawiki/mediawiki/includes/specialpage/SpecialPage.php(569): LoginSignupSpecialPage->execute(NULL)
#14 /opt/mediawiki/mediawiki/includes/specialpage/SpecialPageFactory.php(568): SpecialPage->run(NULL)
#15 /opt/mediawiki/mediawiki/includes/MediaWiki.php(288): MediaWiki\Special\SpecialPageFactory->executePath(Title, RequestContext)
#16 /opt/mediawiki/mediawiki/includes/MediaWiki.php(860): MediaWiki->performRequest()
#17 /opt/mediawiki/mediawiki/includes/MediaWiki.php(517): MediaWiki->main()
#18 /opt/mediawiki/mediawiki/index.php(46): MediaWiki->run()
#19 {main}
```
and an exception
```
Exception caught inside exception handler: [e87d59dbc125b0732b0ec253] /wiki/Spesial:Opprett_konto Wikimedia\Rdbms\DBTransactionStateError from line 1341 of /opt/mediawiki/mediawiki/includes/libs/rdbms/database/Database.php: Cannot execute query from LinkCache::fetchPageRow while transaction status is ERROR.
Backtrace:
#0 /opt/mediawiki/mediawiki/includes/libs/rdbms/database/Database.php(1127): Wikimedia\Rdbms\Database->assertTransactionStatus(string, string)
#1 /opt/mediawiki/mediawiki/includes/libs/rdbms/database/Database.php(1693): Wikimedia\Rdbms\Database->query(string, string)
#2 /opt/mediawiki/mediawiki/includes/libs/rdbms/database/Database.php(1784): Wikimedia\Rdbms\Database->select(string, array, array, string, array, array)
#3 /opt/mediawiki/mediawiki/includes/cache/LinkCache.php(312): Wikimedia\Rdbms\Database->selectRow(string, array, array, string)
#4 /opt/mediawiki/mediawiki/includes/cache/LinkCache.php(270): LinkCache->fetchPageRow(Wikimedia\Rdbms\DatabasePostgres, Title)
#5 /opt/mediawiki/mediawiki/includes/Title.php(3575): LinkCache->addLinkObj(Title)
#6 /opt/mediawiki/mediawiki/includes/Revision/RevisionStore.php(2719): Title->getArticleID()
#7 /opt/mediawiki/mediawiki/includes/Revision.php(1308): MediaWiki\Revision\RevisionStore->getKnownCurrentRevision(Title, integer)
#8 /opt/mediawiki/mediawiki/includes/cache/MessageCache.php(1117): Revision::newKnownCurrent(Wikimedia\Rdbms\DatabasePostgres, Title)
#9 /opt/mediawiki/mediawiki/includes/libs/objectcache/WANObjectCache.php(1277): MessageCache->{closure}(boolean, integer, array, NULL)
#10 /opt/mediawiki/mediawiki/includes/libs/objectcache/WANObjectCache.php(1150): WANObjectCache->doGetWithSetCallback(string, integer, Closure, array)
#11 /opt/mediawiki/mediawiki/includes/cache/MessageCache.php(1143): WANObjectCache->getWithSetCallback(string, integer, Closure)
#12 /opt/mediawiki/mediawiki/includes/libs/objectcache/BagOStuff.php(168): MessageCache->{closure}()
#13 /opt/mediawiki/mediawiki/includes/cache/MessageCache.php(1145): BagOStuff->getWithSetCallback(string, integer, Closure)
#14 /opt/mediawiki/mediawiki/includes/cache/MessageCache.php(1061): MessageCache->loadCachedMessagePageEntry(string, string, string)
#15 /opt/mediawiki/mediawiki/includes/cache/MessageCache.php(958): MessageCache->getMsgFromNamespace(string, string)
#16 /opt/mediawiki/mediawiki/includes/cache/MessageCache.php(928): MessageCache->getMessageForLang(LanguageEn, string, boolean, array)
#17 /opt/mediawiki/mediawiki/includes/cache/MessageCache.php(870): MessageCache->getMessageFromFallbackChain(LanguageEn, string, boolean)
#18 /opt/mediawiki/mediawiki/includes/Message.php(1299): MessageCache->get(string, boolean, LanguageEn)
#19 /opt/mediawiki/mediawiki/includes/Message.php(851): Message->fetchMessage()
#20 /opt/mediawiki/mediawiki/includes/Message.php(943): Message->toString(string)
#21 /opt/mediawiki/mediawiki/includes/exception/MWExceptionRenderer.php(132): Message->text()
#22 /opt/mediawiki/mediawiki/includes/exception/MWExceptionRenderer.php(53): MWExceptionRenderer::reportHTML(Wikimedia\Rdbms\DBQueryError)
#23 /opt/mediawiki/mediawiki/includes/exception/MWExceptionHandler.php(98): MWExceptionRenderer::output(Wikimedia\Rdbms\DBQueryError, integer)
#24 /opt/mediawiki/mediawiki/includes/exception/MWExceptionHandler.php(172): MWExceptionHandler::report(Wikimedia\Rdbms\DBQueryError)
#25 /opt/mediawiki/mediawiki/includes/MediaWiki.php(544): MWExceptionHandler::handleException(Wikimedia\Rdbms\DBQueryError)
#26 /opt/mediawiki/mediawiki/index.php(46): MediaWiki->run()
#27 {main}
```
something is very broken in our Mediawiki installation

**Comment by slunke** [comment]
It possible to create a user if we change the sql insert and use postgresql cli.
We added user_id as column and the next id (in this case 344) as value.
INSERT INTO "mwuser" (**user_id**,user_name,user_password,user_newpassword,user_email,user_email_authenticated,user_real_name,user_token,user_registration,user_editcount,user_touched) VALUES (**344**,'Tingo-test','','','',NULL,'','63ee74de94fabbf95b75103c126d6a27','2019-03-26 15:43:54+00','0','2019-03-26 15:43:59+00')

We suspect something wrong in the code that creates the sql statement.

**Comment by tingox** [comment]
looks like something has gone wrong with the mwuser table in the database.
```
mediawiki=> select column_default from information_schema.columns where table_name='mwuser' and column_name='user_id';
-[ RECORD 1 ]--+-
column_default | 

```
no value for column_default. Compare with another table which has a sequence as it's default
```
mediawiki=> select column_default from information_schema.columns where table_name='actor' and column_name='actor_id';
-[ RECORD 1 ]--+----------------------------------------
column_default | nextval('actor_actor_id_seq'::regclass)

```
so perhaps mwuser should have one too.

**Comment by tingox** [comment]
first we took a backup of the database with pg_dump.
control
mediawiki=> select column_default from information_schema.columns where table_name='mwuser' and column_name='user_id';
-[ RECORD 1 ]--+-
column_default | 

change stuff
mediawiki=> ALTER TABLE mwuser ALTER COLUMN user_id SET DEFAULT nextval('user_user_id_seq');
ALTER TABLE

verify
mediawiki=> select column_default from information_schema.columns where table_name='mwuser' and column_name='user_id';
-[ RECORD 1 ]--+--------------------------------------
column_default | nextval('user_user_id_seq'::regclass)
now to test

**Comment by tingox** [comment]
and now we can add a user
mediawiki=> INSERT INTO "mwuser" (user_name,user_password,user_newpassword,user_email,user_email_authenticated,user_real_name,user_token,user_registration,user_editcount,user_touched) VALUES ('Tingo-test4','','','',NULL,'Torfinn 4 Testbruker','79fccbaba536a93256bd191b1763d450','2019-05-02 19:21:40+00','0','2019-05-02 19:21:45+00');
INSERT 0 1
mediawiki=> select currval(pg_get_serial_sequence('mwuser','user_id'));
-[ RECORD 1 ]
currval | 346

**Comment by tingox** [comment]
I can also create an account in Mediawiki now:
Notice: Undefined variable: username in /opt/mediawiki/mediawiki/extensions/p2k12-auth.php on line 70

Notice: Undefined offset: 4 in /opt/mediawiki/mediawiki/extensions/p2k12-auth.php on line 80
Account created

The user account for Tingo-test5 (talk) has been created.

Return to Spesial:Opprett konto.

**Comment by slunke** [comment]
The referenced AuthPlugin.php can be found here:
https://phabricator.wikimedia.org/source/mediawiki/browse/master/includes/AuthPlugin.php;0f1858321c37f48d8c01d0d113e99d4441d14594

**Comment by tingox** [comment]
AuthPlugin.php looks like this
[AuthPlugin.php.txt](https://github.com/bitraf/infrastructure/files/3139572/AuthPlugin.php.txt)

**Comment by tingox** [comment]
today, users that couldn't log in to the wiki earlier, can log in, and edit, create pages and so on. Unfortunately, we haven't figured out which change (or changes) that fixed it yet.

**Comment by tingox** [comment]
closing this, as the wiki has been working for some time.
